Repository jakartaee/specifications, pull requests merged in 2019-09, with the labels that each got.

#29 Jakarta JSON Processing 1.1
  jsonp/1.1/_index.md
  jsonp/1.1/jsonp-spec-1.1.html
  jsonp/1.1/jsonp-spec-1.1.pdf
  jsonp/_index.md
Labels: approved, ballot, final

#31 Jakarta Persistence 2.2
  persistence/2.2/_index.md
  persistence/2.2/persistence_2.2.html
  persistence/2.2/persistence_2.2.pdf
  persistence/_index.md
Labels: approved, ballot, final

#38 Jakarta Authentication 1.1
  authentication/1.1/_index.md
  authentication/1.1/authentication-spec-1.1.html
  authentication/1.1/authentication-spec-1.1.pdf
  authentication/_index.md
Labels: approved, ballot, final

#77 Jakarta Server Pages 2.3
  pages/2.3/_index.md
  pages/2.3/pages-spec-2.3.html
  pages/2.3/pages-spec-2.3.pdf
  pages/_index.md
Labels: approved, ballot, final

#25 Jakarta Transactions 1.3
  transactions/1.3/_index.md
  transactions/1.3/transactions-spec-1.3.html
  transactions/1.3/transactions-spec-1.3.pdf
  transactions/_index.md
Labels: approved, ballot, final

#7 Jakarta RESTful Web Services 2.1
  restful-ws/2.1/_index.md
  restful-ws/2.1/restful-ws-spec-2.1.html
  restful-ws/2.1/restful-ws-spec-2.1.pdf
  restful-ws/_index.md
Labels: approved, ballot, final

#40 Jakarta Expression Language 3.0
  expression-language/3.0/_index.md
  expression-language/3.0/expression-language-spec-3.0.html
  expression-language/3.0/expression-language-spec-3.0.pdf
  expression-language/_index.md
Labels: approved, ballot, final

#14 Jakarta Batch 1.0 Specification
  batch/1.0/_index.md
  batch/1.0/batch-spec-1.0.html
  batch/1.0/batch-spec-1.0.pdf
  batch/_index.md
Labels: approved, ballot, final

#67 Jakarta XML RPC 1.1 spec
  xml-rpc/1.1/_index.md
  xml-rpc/1.1/xml-rpc-spec-1.1.html
  xml-rpc/1.1/xml-rpc-spec-1.1.pdf
  xml-rpc/_index.md
Labels: approved, ballot, final

#61 Jakarta Servlet 4.0
  servlet/4.0/_index.md
  servlet/4.0/servlet-spec-4.0.html
  servlet/4.0/servlet-spec-4.0.pdf
  servlet/_index.md
Labels: approved, ballot, final

#33 Jakarta Connectors 1.7
  connectors/1.7/_index.md
  connectors/1.7/connectors-spec-1.7.html
  connectors/1.7/connectors-spec-1.7.pdf
  connectors/_index.md
Labels: approved, ballot, final

#88 Jakarta XML Registries 1.0 Spec
  xml-registries/1.0/_index.md
  xml-registries/1.0/xml-registries-spec-1.0.html
  xml-registries/1.0/xml-registries-spec-1.0.pdf
  xml-registries/_index.md
Labels: approved, ballot, final

#27 Jakarta JSON Binding 1.0
  jsonb/1.0/_index.md
  jsonb/1.0/jsonb-spec-1.0.html
  jsonb/1.0/jsonb-spec-1.0.pdf
  jsonb/_index.md
Labels: approved, ballot, final

#79 Jakarta WebSocket 1.1
  websocket/1.1/_index.md
  websocket/1.1/websocket-spec-1.1.html
  websocket/1.1/websocket-spec-1.1.pdf
  websocket/_index.md
Labels: approved, ballot, final

#24 Jakarta Debugging Support for Other Languages 1.0 Spec
  debugging/1.0/_index.md
  debugging/1.0/debugging_1.0.html
  debugging/1.0/debugging_1.0.pdf
  debugging/_index.md
Labels: approved, ballot, final

#22 Jakarta Standard Tag Library 1.2 Spec
  tags/1.2/_index.md
  tags/1.2/tags-1.2-spec.html
  tags/1.2/tags-1.2-spec.pdf
  tags/_index.md
Labels: ballot, final

#54 Jakarta Authorization 1.5
  authorization/1.5/_index.md
  authorization/1.5/authorization-spec-1.5.html
  authorization/1.5/authorization-spec-1.5.pdf
  authorization/_index.md
Labels: approved, ballot, final

#55 Jakarta Authorization 1.5 apidocs
  authorization/1.5/apidocs/allclasses-frame.html
  authorization/1.5/apidocs/allclasses-noframe.html
  authorization/1.5/apidocs/constant-values.html
  authorization/1.5/apidocs/deprecated-list.html
  authorization/1.5/apidocs/doc-files/speclicense.html
  authorization/1.5/apidocs/help-doc.html
  authorization/1.5/apidocs/index-all.html
  authorization/1.5/apidocs/index.html
  authorization/1.5/apidocs/javax/security/jacc/EJBMethodPermission.html
  authorization/1.5/apidocs/javax/security/jacc/EJBRoleRefPermission.html
  authorization/1.5/apidocs/javax/security/jacc/PolicyConfiguration.html
  authorization/1.5/apidocs/javax/security/jacc/PolicyConfigurationFactory.html
  authorization/1.5/apidocs/javax/security/jacc/PolicyContext.html
  authorization/1.5/apidocs/javax/security/jacc/PolicyContextException.html
  authorization/1.5/apidocs/javax/security/jacc/PolicyContextHandler.html
  authorization/1.5/apidocs/javax/security/jacc/WebResourcePermission.html
  authorization/1.5/apidocs/javax/security/jacc/WebRoleRefPermission.html
  authorization/1.5/apidocs/javax/security/jacc/WebUserDataPermission.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/EJBMethodPermission.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/EJBRoleRefPermission.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/PolicyConfiguration.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/PolicyConfigurationFactory.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/PolicyContext.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/PolicyContextException.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/PolicyContextHandler.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/WebResourcePermission.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/WebRoleRefPermission.html
  authorization/1.5/apidocs/javax/security/jacc/class-use/WebUserDataPermission.html
  authorization/1.5/apidocs/javax/security/jacc/package-frame.html
  authorization/1.5/apidocs/javax/security/jacc/package-summary.html
  authorization/1.5/apidocs/javax/security/jacc/package-tree.html
  authorization/1.5/apidocs/javax/security/jacc/package-use.html
  authorization/1.5/apidocs/overview-tree.html
  authorization/1.5/apidocs/package-list
  authorization/1.5/apidocs/script.js
  authorization/1.5/apidocs/serialized-form.html
  authorization/1.5/apidocs/stylesheet.css
Labels: approved, ballot, final

#42 Jakarta Security 1.0
  security/1.0/_index.md
  security/1.0/security-spec-1.0.html
  security/1.0/security-spec-1.0.pdf
  security/_index.md
Labels: approved, ballot, final

#21 Jakarta EE Web Profile 8 Specification
  webprofile/8/_index.md
  webprofile/8/webprofile-spec-8.html
  webprofile/8/webprofile-spec-8.pdf
  webprofile/_index.md
Labels: approved, ballot, final, platform

#91 Jakarta Enterprise Web Services 1.4 Specification
  enterprise-ws/1.4/_index.md
  enterprise-ws/1.4/enterprise-ws-spec-1.4.html
  enterprise-ws/1.4/enterprise-ws-spec-1.4.pdf
  enterprise-ws/_index.md
Labels: approved, ballot, final, platform

#82 Jakarta Server Faces 2.3
  faces/2.3/_index.md
  faces/2.3/faces-spec-2.3.html
  faces/2.3/faces-spec-2.3.pdf
  faces/_index.md
Labels: approved, ballot, final

#19 Managed Beans 1.0 Specification
  managedbeans/1.0/_index.md
  managedbeans/1.0/managedbeans-spec-1.0.html
  managedbeans/1.0/managedbeans-spec-1.0.pdf
  managedbeans/_index.md
Labels: approved, ballot, final, platform

#75 Jakarta Management API 1.1 Specification
  management/1.1/_index.md
  management/1.1/management-spec-1.1.html
  management/1.1/management-spec-1.1.pdf
  management/_index.md
Labels: approved, ballot, final, platform

#52 Jakarta Interceptors 1.2
  interceptors/1.2/_index.md
  interceptors/1.2/interceptors-spec-1.2.html
  interceptors/1.2/interceptors-spec-1.2.pdf
  interceptors/_index.md
Labels: approved, ballot, final, platform

#53 Jakarta Interceptors 1.2 apidocs
  interceptors/1.2/apidocs/allclasses-frame.html
  interceptors/1.2/apidocs/allclasses-noframe.html
  interceptors/1.2/apidocs/constant-values.html
  interceptors/1.2/apidocs/deprecated-list.html
  interceptors/1.2/apidocs/doc-files/speclicense.html
  interceptors/1.2/apidocs/help-doc.html
  interceptors/1.2/apidocs/index-all.html
  interceptors/1.2/apidocs/index.html
  interceptors/1.2/apidocs/javax/interceptor/AroundConstruct.html
  interceptors/1.2/apidocs/javax/interceptor/AroundInvoke.html
  interceptors/1.2/apidocs/javax/interceptor/AroundTimeout.html
  interceptors/1.2/apidocs/javax/interceptor/ExcludeClassInterceptors.html
  interceptors/1.2/apidocs/javax/interceptor/ExcludeDefaultInterceptors.html
  interceptors/1.2/apidocs/javax/interceptor/Interceptor.Priority.html
  interceptors/1.2/apidocs/javax/interceptor/Interceptor.html
  interceptors/1.2/apidocs/javax/interceptor/InterceptorBinding.html
  interceptors/1.2/apidocs/javax/interceptor/Interceptors.html
  interceptors/1.2/apidocs/javax/interceptor/InvocationContext.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/AroundConstruct.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/AroundInvoke.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/AroundTimeout.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/ExcludeClassInterceptors.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/ExcludeDefaultInterceptors.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/Interceptor.Priority.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/Interceptor.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/InterceptorBinding.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/Interceptors.html
  interceptors/1.2/apidocs/javax/interceptor/class-use/InvocationContext.html
  interceptors/1.2/apidocs/javax/interceptor/package-frame.html
  interceptors/1.2/apidocs/javax/interceptor/package-summary.html
  interceptors/1.2/apidocs/javax/interceptor/package-tree.html
  interceptors/1.2/apidocs/javax/interceptor/package-use.html
  interceptors/1.2/apidocs/overview-tree.html
  interceptors/1.2/apidocs/package-list
  interceptors/1.2/apidocs/script.js
  interceptors/1.2/apidocs/stylesheet.css
Labels: approved, ballot, final, platform
