Repository jakartaee/specifications, pull requests merged in 2020-06, with the labels that each got.

#155 Create milestone draft for RESTful WS 3.0.0-M1
  restful-ws/3.0/_index.md
  restful-ws/3.0/restful-ws-spec-3.0-M1.html
  restful-ws/3.0/restful-ws-spec-3.0-M1.pdf
Labels: draft, wave:4

#144 Jakarta Annotation 2.0 milestone draft
  annotations/2.0/_index.md
  annotations/2.0/annotations-spec-2.0-RC1.html
  annotations/2.0/annotations-spec-2.0-RC1.pdf
Labels: draft, wave:0

#162 Jakarta XML WS 3.0 Draft
  xml-web-services/3.0/_index.md
  xml-web-services/3.0/xml-ws-spec-3.0-RC3.html
  xml-web-services/3.0/xml-ws-spec-3.0-RC3.pdf
Labels: wave:3

#160 Jakarta SOAP 2.0 Draft
  soap-attachments/2.0/_index.md
  soap-attachments/2.0/soap-spec-2.0-RC3.html
  soap-attachments/2.0/soap-spec-2.0-RC3.pdf
Labels: wave:1

#158 Jakarta WS Metadata 3.0 Draft
  web-services-metadata/3.0/_index.md
  web-services-metadata/3.0/ws-metadata-spec-3.0-RC2.html
  web-services-metadata/3.0/ws-metadata-spec-3.0-RC2.pdf
Labels: wave:0

#146 Json Processing 2.0 specification milestone draft
  jsonp/2.0/_index.md
Labels: wave:1

#181 Json Binding 2.0 specification milestone draft
  jsonb/2.0/_index.md
  jsonb/2.0/jsonb-spec-2.0-RC2.html
  jsonb/2.0/jsonb-spec-2.0-RC2.pdf
Labels: wave:2

#168 Jakarta Enterprise WS 2.0 Draft
  enterprise-ws/2.0/_index.md
  enterprise-ws/2.0/enterprise-ws-spec-2.0-RC1.html
  enterprise-ws/2.0/enterprise-ws-spec-2.0-RC1.pdf
Labels: draft, wave:5

#182 Jakarta Batch 2.0 Milestone draft
  batch/2.0/_index.md
  batch/2.0/batch-spec-2.0-draft.html
  batch/2.0/batch-spec-2.0-draft.pdf
Labels: draft, wave:4

#193 Jakarta Security 2.0 Draft
  security/2.0/_index.md
  security/2.0/security-spec-2.0.0-SNAPSHOT.html
  security/2.0/security-spec-2.0.0-SNAPSHOT.pdf
Labels: wave:6

#189 Jakarta Authentication 2.0 Draft
  authentication/2.0/_index.md
  authentication/2.0/authentication-spec-2.0-SNAPSHOT.html
  authentication/2.0/authentication-spec-2.0-SNAPSHOT.pdf
Labels: wave:2

#191 Jakarta Authorization 2.0 Draft
  authorization/2.0/_index.md
  authorization/2.0/authorization-spec-2.0-SNAPSHOT.html
  authorization/2.0/authorization-spec-2.0-SNAPSHOT.pdf
Labels: wave:2

#195 Jakarta Servlet 5.0 Draft
  servlet/5.0/_index.md
  servlet/5.0/servlet-spec-5.0-SNAPSHOT.html
  servlet/5.0/servlet-spec-5.0-SNAPSHOT.pdf
Labels: wave:1

#170 Jakarta Concurrency 2.0.0-RC2 api javadocs
  concurrency/2.0/apidocs/allclasses-frame.html
  concurrency/2.0/apidocs/allclasses-noframe.html
  concurrency/2.0/apidocs/constant-values.html
  concurrency/2.0/apidocs/deprecated-list.html
  concurrency/2.0/apidocs/doc-files/speclicense.html
  concurrency/2.0/apidocs/help-doc.html
  concurrency/2.0/apidocs/index-all.html
  concurrency/2.0/apidocs/index.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/AbortedException.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ContextService.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/LastExecution.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManageableThread.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManagedExecutorService.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManagedExecutors.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManagedScheduledExecutorService.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManagedTask.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManagedTaskListener.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/ManagedThreadFactory.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/SkippedException.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/Trigger.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/AbortedException.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ContextService.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/LastExecution.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManageableThread.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManagedExecutorService.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManagedExecutors.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManagedScheduledExecutorService.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManagedTask.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManagedTaskListener.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/ManagedThreadFactory.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/SkippedException.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/class-use/Trigger.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/package-frame.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/package-summary.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/package-tree.html
  concurrency/2.0/apidocs/jakarta/enterprise/concurrent/package-use.html
  concurrency/2.0/apidocs/overview-tree.html
  concurrency/2.0/apidocs/package-list
  concurrency/2.0/apidocs/script.js
  concurrency/2.0/apidocs/serialized-form.html
  concurrency/2.0/apidocs/stylesheet.css
Labels: wave:0

#201 Jakarta Messaging 3.0 Draft
  messaging/3.0/_index.md
  messaging/3.0/messaging-spec-3.0-SNAPSHOT.html
  messaging/3.0/messaging-spec-3.0-SNAPSHOT.pdf
Labels: draft, wave:0

#206 Update for EL-4.0.0-RC2 part one (spec documents)
  expression-language/4.0/_index.md
  expression-language/4.0/expression-language-spec-4.0-RC2.html
  expression-language/4.0/expression-language-spec-4.0-RC2.pdf
Labels: draft, wave:1

#210 Jakarta Interceptors 2.0 Draft
  interceptors/2.0/_index.md
  interceptors/2.0/interceptors-spec-2.0-SNAPSHOT.html
  interceptors/2.0/interceptors-spec-2.0-SNAPSHOT.pdf
Labels: wave:1

#213 Update for JDSOL 2.0-RC2 part one (there is no part two)
  debugging/2.0/_index.md
  debugging/2.0/jdsol-spec-2.0-RC2.html
  debugging/2.0/jdsol-spec-2.0-RC2.pdf
Labels: wave:2

#214 JSP 3.0.0-RC2 part one
  pages/3.0/_index.md
  pages/3.0/server-pages-spec-3.0-RC2.html
  pages/3.0/server-pages-spec-3.0-RC2.pdf
Labels: wave:2

#218 Jakarta Tags 2.0 Draft
  tags/2.0/_index.md
  tags/2.0/jstl-spec-2.0-SNAPSHOT.html
  tags/2.0/jstl-spec-2.0-SNAPSHOT.pdf
Labels: wave:5

#216 Jakarta Activation 2.0 Draft
  activation/2.0/_index.md
  activation/2.0/activation-spec-2.0-RC3.html
  activation/2.0/activation-spec-2.0-RC3.pdf
Labels: wave:1
