Repository jakartaee/specifications, pull requests merged in 2021-05, with the labels that each got.

#348 Jakarta JSON Binding 2.1 Plan Review
  jsonb/2.1/_index.md
Labels: approved, plan review

#353 Jakarta Mail 2.1 Plan Review
  mail/2.1/_index.md
Labels: approved, plan review

#355 Jakarta Faces 4.0 Plan Review
  faces/4.0/_index.md
Labels: approved, plan review

#358 Jakarta SOAP with Attachments 3.0 Plan Review
  soap-attachments/3.0/_index.md
Labels: approved, plan review

#363 Jakarta EL 5.0 plan review
  expression-language/5.0/_index.md
Labels: approved, plan review

#347 Jakarta MVC 2.1 Plan Review
  mvc/2.1/_index.md
Labels: ballot, plan review

#365 Jakarta WebSocket 2.1 Plan Review
  websocket/2.1/_index.md
Labels: ballot, plan review

#349 Jakarta EE Core Profile Creation and Plan Review
  coreprofile/10/_index.md
  coreprofile/_index.md
Labels: approved, creation review, plan review

#368 Jakarta Concurrency 3.0 Plan Review
  concurrency/3.0/_index.md
Labels: ballot, plan review

#384 Jakarta Config creation review
  config/_index.md
Labels: approved, ballot, creation review

#380 Jakarta Messaging 3.1 Plan Review
  messaging/3.1/_index.md
Labels: approved, plan review
