Repository jakartaee/specifications, pull requests merged in 2021-06, with the labels that each got.

#351 Jakarta RESTful Web Services 4.0 Plan Review
  restful-ws/4.0/_index.md
Labels: approved, plan review

#361 Jakarta Authorization 2.1 Plan Review
  authorization/2.1/_index.md
Labels: approved, complete, plan review

#356 Jakarta Authentication 3.0 Plan Review
  authentication/3.0/_index.md
Labels: plan review

#381 Jakarta Batch 2.1 Plan Review
  batch/2.1/_index.md
Labels: plan review

#354 Jakarta JSON Processing 2.1 Plan Review
  jsonp/2.1/_index.md
Labels: approved, ballot, plan review

#364 Jakarta Standard Tag Library 3.0 Draft Plan
  tags/3.0/_index.md
Labels: approved, ballot, plan review

#366 Jakarta JSP 3.1 Plan Review
  pages/3.1/_index.md
Labels: approved, ballot, plan review
