Repository jakartaee/specifications, pull requests merged in 2025-04, with the labels that each got.

#808 Create Jakarta Query
  query/1.0/_index.md
  query/_index.md
Labels: approved, creation review

#804 Jakarta Pages 4.1 Plan Review
  pages/4.1/_index.md
Labels: approved, plan review

#806 Jakarta WebSocket 2.3.0 Plan Review
  websocket/2.3/_index.md
Labels: approved, plan review

#805 Jakarta Expression Language 6.1.0 Plan Review
  expression-language/6.1/_index.md
Labels: ballot, approved, plan review

#801 Jakarta Faces 5.0 Plan Review
  faces/5.0/_index.md
Labels: approved, plan review

#810 Jakarta Concurrency 3.2 Plan Review
  concurrency/3.2/_index.md
Labels: approved, plan review

#818 JSON Binding 3.1 Plan Review
  jsonb/3.1/_index.md
Labels: approved, plan review

#817 Initial plan for Jakarta Transactions 2.1
  transactions/2.1/_index.md
Labels: approved, plan review

#822 Release plan for Persistence 4.0
  persistence/4.0/_index.md
Labels: approved, plan review

#823 Jakarta RESTful Web Services 5.0 Plan Review
  restful-ws/5.0/_index.md
Labels: approved, plan review

#834 Plan for Jakarta NoSQL 1.1
  nosql/1.1/_index.md
Labels: approved, plan review

#830 Jakarta Batch 2.2 Plan Review
  batch/2.2/_index.md
Labels: approved, plan review
