Repository jakartaee/specifications, pull requests merged in 2025-05, with the labels that each got.

#835 Jakarta Annotations 3.1 Plan Review
  annotations/3.1/_index.md
Labels: ballot, plan review

#825 Jakarta Validation 4.0 plan review information
  bean-validation/4.0/_index.md
Labels: approved, plan review

#831 Security 5.0 plan
  security/5.0/_index.md
Labels: ballot, plan review

#838 Creates the Jakarta Portlet Bridge project (renamed from Jakarta Faces Bridge)
  faces-bridge/7.0/_index.md
  faces-bridge/_index.md
Labels: approved, plan review, creation review

#837 Creates the Jakarta Portlet project:
  portlet/4.0/_index.md
  portlet/_index.md
Labels: approved, plan review, creation review

#828 Jakarta EE Web Profile 12 release plan
  webprofile/12/_index.md
Labels: approved, plan review

#842 Jakarta Mail 2.2 Plan Review
  mail/2.2/_index.md
Labels: final, ballot, approved, plan review

#836 Jakarta JSON Processing 2.2 Plan Review
  jsonp/2.2/_index.md
Labels: ballot, complete, plan review

#824 Jakarta Standard Tag Library 3.1.0 plan review
  tags/3.1/_index.md
Labels: ballot, complete, plan review

#841 Jakarta Activation 2.2 Plan Review
  activation/2.2/_index.md
Labels: approved, plan review
